"""Add programme_id to users

Revision ID: 1aaef8a9e827
Revises: 4178cb1d7080
Create Date: 2026-08-25 21:06:54.527349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1aaef8a9e827'
down_revision: Union[str, Sequence[str], None] = '4178cb1d7080'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('programme_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'programmes', ['programme_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'programme_id')
    # ### end Alembic commands ###
