"""name fk_users_programme_id constraint explicitly

Revision ID: a7ec7d43d3a0
Revises: 1aaef8a9e827
Create Date: 2026-09-14 23:26:25.805976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7ec7d43d3a0'
down_revision: Union[str, Sequence[str], None] = '1aaef8a9e827'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
